language: php

os: linux

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install
  - if [[ "$BUILD" != true ]]; then
      composer require satooshi/php-coveralls:~0.6@stable;
    fi

before_script:
  - if [[ "$BUILD" != true ]]; then
      mkdir -p build/logs;
      git clone https://github.com/octobercms/october.git;
      mkdir -p ./october/plugins/lovata/toolbox;
      mv !(october) october/plugins/lovata/toolbox;
      cd october;
      composer self-update;
      travis_retry composer install;
      cd plugins/lovata/toolbox;
    fi

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - if [[ "$BUILD" != true && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then
      php vendor/bin/coveralls -v;
    fi

jobs:
  include:
    - stage: Release
      env:
        - BUILD=true
      script:
        - NAME="toolbox"
        - zip -r $NAME ./ -x .git/\* -x .gitignore -x .travis.yml -x crowdin.yml -x .editorconfig -x .codeclimate.yml -x PHPMD_custom.xml
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
            NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
            mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        edge: true
        file: "$NEW_NAME.zip"
        on:
          tags: true
          repo: oc-shopaholic/oc-toolbox-plugin
